# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_test_nlopt <- function() {
    .Call(`_colvR_cpp_test_nlopt`)
}

Elbo_grad_Rcpp <- function(data, params, tolxi) {
    .Call(`_colvR_Elbo_grad_Rcpp`, data, params, tolxi)
}

Elbo <- function(data, params, tolxi) {
    .Call(`_colvR_Elbo`, data, params, tolxi)
}

Grad <- function(data, params, tolxi) {
    .Call(`_colvR_Grad`, data, params, tolxi)
}

nlopt_optimize_ZIP <- function(data, params, config, tolxi) {
    .Call(`_colvR_nlopt_optimize_ZIP`, data, params, config, tolxi)
}

nlopt_optimize_ZIP_M <- function(data, params, config, tolxi) {
    .Call(`_colvR_nlopt_optimize_ZIP_M`, data, params, config, tolxi)
}

nlopt_optimize_ZIP_VE <- function(data, params, config, tolxi) {
    .Call(`_colvR_nlopt_optimize_ZIP_VE`, data, params, config, tolxi)
}

nlopt_optimize_ZIP_Steps <- function(data, params, config, tolxi, active_block_list) {
    .Call(`_colvR_nlopt_optimize_ZIP_Steps`, data, params, config, tolxi, active_block_list)
}

nlopt_optimize_ZIP_q0 <- function(data, params, config, tolxi) {
    .Call(`_colvR_nlopt_optimize_ZIP_q0`, data, params, config, tolxi)
}

nlopt_optimize_rank_miss <- function(data, params, config) {
    .Call(`_colvR_nlopt_optimize_rank_miss`, data, params, config)
}

nlopt_optimize_rank_cov <- function(data, params, config) {
    .Call(`_colvR_nlopt_optimize_rank_cov`, data, params, config)
}

Elbo_grad_logS_Rcpp <- function(data, params, tolxi) {
    .Call(`_colvR_Elbo_grad_logS_Rcpp`, data, params, tolxi)
}

nlopt_optimize_ZIP_logS <- function(data, params, config, tolxi) {
    .Call(`_colvR_nlopt_optimize_ZIP_logS`, data, params, config, tolxi)
}

cpp_test_packing <- function() {
    .Call(`_colvR_cpp_test_packing`)
}

MatrixToVector <- function(matrix) {
    .Call(`_colvR_MatrixToVector`, matrix)
}

VectorToMatrix <- function(vector, n, p) {
    .Call(`_colvR_VectorToMatrix`, vector, n, p)
}

