# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_test_nlopt <- function() {
    .Call(`_colvR_cpp_test_nlopt`)
}

Elbo_grad_Rcpp <- function(data, params) {
    .Call(`_colvR_Elbo_grad_Rcpp`, data, params)
}

Elbo <- function(data, params) {
    .Call(`_colvR_Elbo`, data, params)
}

Grad <- function(data, params) {
    .Call(`_colvR_Grad`, data, params)
}

nlopt_optimize_ZIP <- function(data, params, config) {
    .Call(`_colvR_nlopt_optimize_ZIP`, data, params, config)
}

Elbo_grad_logS_Rcpp <- function(data, params) {
    .Call(`_colvR_Elbo_grad_logS_Rcpp`, data, params)
}

nlopt_optimize_ZIP_logS <- function(data, params, config) {
    .Call(`_colvR_nlopt_optimize_ZIP_logS`, data, params, config)
}

cpp_test_packing <- function() {
    .Call(`_colvR_cpp_test_packing`)
}

MatrixToVector <- function(matrix) {
    .Call(`_colvR_MatrixToVector`, matrix)
}

VectorToMatrix <- function(vector, n, p) {
    .Call(`_colvR_VectorToMatrix`, vector, n, p)
}

